name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install libstdc++6
      run: |
        sudo apt-get update
        sudo apt-get install -y libstdc++6

    - name: Install aidl
      run: |
        sudo apt-get update
        sudo apt-get install -y aidl

    - name: Install Android SDK and tools
      run: |
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
        mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "$HOME/Android/Sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/Android/Sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/Android/Sdk/emulator" >> $GITHUB_PATH
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;35.0.0" "system-images;android-30;default;x86_64"

    - name: Verify Aidl Installation
      run: |
        if ! command -v aidl &> /dev/null; then
          echo "Error: aidl is not installed. Please check the Build-Tools installation.";
          exit 1;
        fi

    - name: Run Buildozer
      run: |
        export ANDROID_HOME=$HOME/Android/Sdk
        export PATH=$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug
        
